FROM node:18-alpine as build
WORKDIR /app
COPY frontend/package.json ./
RUN npm install
COPY frontend/ .
RUN npm run build

FROM nginx:stable-alpine
COPY --from=build /app/build /usr/share/nginx/html
COPY devops/nginx/default.conf /etc/nginx/conf.d/default.conf
